### PR TITLE
Remove WAF

### PR DESCRIPTION
**Pull request by martinpham97**
COM-44

# Notes

- Remove WAF as it is not in the scope of the threat model

### CODE REVIEW

**Review by ecl1ipse — CHANGES_REQUESTED** [review]
I'm not sure why but when I try to run python cdk.py, I get an error psycopg2. I also get an error when I try to do pip3 install -r requirements.txt related to psycopg. Is there more involved in installing psycopg that just pip installing? Other than that it looks good.

**Comment by martinpham97** [comment]
> I'm not sure why but when I try to run python cdk.py, I get an error psycopg2. I also get an error when I try to do pip3 install -r requirements.txt related to psycopg. Is there more involved in installing psycopg that just pip installing? Other than that it looks good.

I'm not sure how the error came up. What exactly was the error?

**Comment by ecl1ipse** [comment]
> > I'm not sure why but when I try to run python cdk.py, I get an error psycopg2. I also get an error when I try to do pip3 install -r requirements.txt related to psycopg. Is there more involved in installing psycopg that just pip installing? Other than that it looks good.
> 
> I'm not sure how the error came up. What exactly was the error?

For python cdk.py it was 'No module named 'psycopg2''. For pip install it was:
ERROR: Command errored out with exit status 1:
     command: /home/silver/projects/IR-CDK-Stacks/.env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rrfsq3qp/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rrfsq3qp/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info
         cwd: /tmp/pip-install-rrfsq3qp/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ecl1ipse** [comment]
> > > I'm not sure why but when I try to run python cdk.py, I get an error psycopg2. I also get an error when I try to do pip3 install -r requirements.txt related to psycopg. Is there more involved in installing psycopg that just pip installing? Other than that it looks good.
> > 
> > 
> > I'm not sure how the error came up. What exactly was the error?
> 
> For python cdk.py it was 'No module named 'psycopg2''. For pip install it was:
> ERROR: Command errored out with exit status 1:
> command: /home/silver/projects/IR-CDK-Stacks/.env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rrfsq3qp/psycopg2/setup.py'"'"'; **file**='"'"'/tmp/pip-install-rrfsq3qp/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info
> cwd: /tmp/pip-install-rrfsq3qp/psycopg2/
> Complete output (23 lines):
> running egg_info
> creating /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info
> writing /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
> writing dependency_links to /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
> writing top-level names to /tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
> writing manifest file '/tmp/pip-install-rrfsq3qp/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
> 
> ```
> Error: pg_config executable not found.
> 
> pg_config is required to build psycopg2 from source.  Please add the directory
> containing pg_config to the $PATH or specify the full executable path with the
> option:
> 
>     python setup.py build_ext --pg-config /path/to/pg_config build ...
> 
> or with the pg_config option in 'setup.cfg'.
> 
> If you prefer to avoid building psycopg2 from source, please install the PyPI
> 'psycopg2-binary' package instead.
> 
> For further information please check the 'doc/src/install.rst' file (also at
> <https://www.psycopg.org/docs/install.html>).
> 
> ----------------------------------------
> ```
> 
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Now I'm getting:
ERROR: Command errored out with exit status 1:
     command: /home/silver/projects/IR-CDK-Stacks/.env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ch8zl8b_/PyGreSQL/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ch8zl8b_/PyGreSQL/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ch8zl8b_/PyGreSQL/pip-egg-info
         cwd: /tmp/pip-install-ch8zl8b_/PyGreSQL/
    Complete output (10 lines):
    /bin/sh: 1: pg_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ch8zl8b_/PyGreSQL/setup.py", line 90, in <module>
        pg_version = pg_version()
      File "/tmp/pip-install-ch8zl8b_/PyGreSQL/setup.py", line 84, in pg_version
        match = re.search(r'(\d+)\.(\d+)', pg_config('version'))
      File "/tmp/pip-install-ch8zl8b_/PyGreSQL/setup.py", line 76, in pg_config
        raise Exception("pg_config tool is not available.")
    Exception: pg_config tool is not available.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

On pip install

**Review by ecl1ipse — APPROVED** [review]
It works now and looks good

**Pull request merged**
